### ISSUE TITLE
Toggle dropdown button in table is hidden

### ISSUE THREAD

**Issue by jimmymchau** [themesberg/th-volt-pro-laravel-admin-dashboard#1]
Greetings... 

I'm having an issue with a dropdown toggle button which seems to be hidden when there is data only in the first row of the table. It appeared only if there is more than one row in the table. 

When clicked, the dropdown menus seem to go underneath the table row. Any help will be appreciated

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products!

We could not recreate the issue. 

Are you encountering this issue on one of the default presentation pages or did you do any customization? 

Thank you.

**Comment by jimmymchau** [comment]
Hello, 

I'm using the default presentation page. Just have removed creator and member roles from the roles management table and left only the Admin role. But the toggle button on the action column seems to go underneath the table row when clicked

**Comment by teamupdivision** [comment]
Hello, 

Sorry for late reply, we fixed the issue. 

Could you re-download the product and let us know if it works now? 

Thank you.

**Comment by jimmymchau** [comment]
Hello, 

It seems to be fixed from the downloaded template. But it is hard to know where you made changes so I can implement them in my ongoing project. Can you assist? I can't restart my whole project so as to adopt these changes. At least I should know where exactly to make changes.

Cheers,
Jimmy

**Comment by teamupdivision** [comment]
Hello, 

We just removed the tailwind class 'overflow-hidden' from resources/views/components/table.blade.php and instead added 'style="overflow-x: clip"' to that element. 

You could just use the corresponding tailwind css class intended for that, we just did not want to make changes to generated css files and opted for a raw "style" tag option instead.

Let me know if there is anything else we can help with or if we can mark this tichet as closed.

Thank you.

**Comment by jimmymchau** [comment]
Hello,

Kindly know that your solution worked. I will close this ticket now.

Thanks for your help.
